import type { Item } from '../types/item'

function addDays(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().slice(0, 10)
}

export const mockItems: Item[] = [
  {
    id: '1',
    name: 'Whole Milk',
    brand: 'Amul',
    category: 'grocery',
    dateType: 'use-by',
    expiryDate: addDays(1),
    packageSize: '1L',
    countOwned: 1,
    reminderLeadDays: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    sources: { name: 'barcode', brand: 'barcode', expiryDate: 'ocr', dateType: 'ocr', category: 'auto' },
  },
  {
    id: '2',
    name: 'Greek Yogurt',
    brand: 'Epigamia',
    category: 'grocery',
    dateType: 'best-before',
    expiryDate: addDays(3),
    packageSize: '200g',
    countOwned: 2,
    reminderLeadDays: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    sources: { name: 'barcode', expiryDate: 'ocr', dateType: 'ocr' },
  },
  {
    id: '3',
    name: 'Ibuprofen 200mg',
    brand: 'Advil',
    category: 'medicine',
    dateType: 'expiry',
    expiryDate: addDays(45),
    packageSize: '24 tablets',
    countOwned: 1,
    reminderLeadDays: 14,
    status: 'active',
    createdAt: new Date().toISOString(),
    sources: { name: 'ocr', expiryDate: 'ocr', dateType: 'manual' },
  },
  {
    id: '4',
    name: 'Hydrating Serum',
    brand: 'The Ordinary',
    category: 'cosmetic',
    dateType: 'pao',
    expiryDate: addDays(180),
    openedOn: addDays(-15),
    paoMonths: 6,
    packageSize: '30ml',
    countOwned: 1,
    reminderLeadDays: 7,
    status: 'active',
    createdAt: new Date().toISOString(),
    sources: { name: 'ocr', dateType: 'manual', expiryDate: 'manual' },
  },
  {
    id: '5',
    name: 'Eggs (dozen)',
    brand: 'Farm Fresh',
    category: 'grocery',
    dateType: 'best-before',
    expiryDate: addDays(0),
    packageSize: '12 ct',
    countOwned: 1,
    reminderLeadDays: 2,
    status: 'active',
    createdAt: new Date().toISOString(),
    sources: { name: 'manual', expiryDate: 'manual', dateType: 'manual' },
  },
  {
    id: '6',
    name: 'Acetaminophen',
    brand: 'Tylenol',
    category: 'medicine',
    dateType: 'expiry',
    expiryDate: addDays(-5),
    packageSize: '50 tablets',
    countOwned: 1,
    reminderLeadDays: 14,
    status: 'active',
    createdAt: new Date().toISOString(),
    sources: { name: 'barcode', brand: 'barcode', expiryDate: 'ocr', dateType: 'ocr' },
  },
]
